/*
  EpdUi.cpp - 200x200 four-colour e-paper user interface
  (part of WaveshareMon, GPL v3, see LICENSE)

  Layout and drawing helpers (icons, trend arrow, mini graph, colour rules)
  derive from M5_NightscoutMon (Martin Lukasek, GPL v3) via M5Stack_xDripMon.
  Panel driver: GxEPD2 (Jean-Marc Zingg), class GxEPD2_154c_GDEM0154F51H,
  whose init sequence matches Waveshare's EPD_1in54g driver.

  Copyright (C) 2026 Patrick Sonnerat
*/
#include <esp_attr.h>
#include "EpdUi.h"
#include "Board.h"
#include "AppConfig.h"
#include "GlucoseState.h"
#include "Alarms.h"
#include "Battery.h"
#include "TimeService.h"
#include "BleObbClient.h"
#include "BleMiBand.h"
#include "BleSetupServer.h"
#include "WebSetup.h"
#include "WifiService.h"
#include "DexcomShareClient.h"
#include "LibreLinkUpClient.h"
#include "PowerCycle.h"
#include "Version.h"
#include <SPI.h>
#include <GxEPD2_4C.h>
#include <Fonts/FreeSans9pt7b.h>
#include <Fonts/FreeSansBold9pt7b.h>
#include <Fonts/FreeSansBold12pt7b.h>
#include <Fonts/FreeSansBold18pt7b.h>
#include "FreeSansBold11pt7b.h"        // generated by Scripts/gfxfont.py (battery %, IOB / COB)
#include "FreeSansBold28pt7b.h"        // generated by Scripts/gfxfont.py, "-".."9" only (the value)

extern const unsigned char bat0_icon16x16[], bat1_icon16x16[], bat2_icon16x16[],
                           bat3_icon16x16[], bat4_icon16x16[], plug_icon16x16[],
                           bluetooth_icon16x16[], wifi2_icon16x16[], clock_icon16x16[],
                           warning_icon16x16[];

EpdUi ui;

#define W 200
#define H 200

// ---- layout (y bands of the glucose screen) ---------------------------------------
#define HDR_H       28            // reading time + status icons (16x16 art drawn at 2x)
#define BAND_TOP    34            // the highlight band (frame / fill): value + trend rows
#define BAND_H      100
#define VAL_TOP     36            // value row (28 pt digits, ~40 px)
#define VAL_H       60
#define VAL_CX      73            // value centred in x 6..140, trend pointer to its right
#define ARROW_CX    166
#define ARROW_CY    (VAL_TOP + VAL_H / 2)
#define TREND_Y     100           // delta (left) + age (right), second row of the band
#define TREND_H     26
#define GRAPH_Y     140           // short graph (left) + info text (right)
#define GRAPH_H     38
#define GRAPH_X     4
#define GRAPH_PTS   24            // 2 h at 5-minute cadence
#define GRAPH_PITCH 3
#define SIDE_X      86
#define SIDE_W      (W - 4 - SIDE_X)
#define BAR_Y       180           // bottom bar: alarm / status
#define BAR_H       (H - BAR_Y)

static GxEPD2_4C<GxEPD2_154c_GDEM0154F51H, GxEPD2_154c_GDEM0154F51H::HEIGHT>
  display(GxEPD2_154c_GDEM0154F51H(PIN_EPD_CS, PIN_EPD_DC, PIN_EPD_RST, PIN_EPD_BUSY));

// ---- primitives ----------------------------------------------------------------

static void drawIcon(int16_t x, int16_t y, const unsigned char *bitmap, uint16_t color) {
  display.drawBitmap(x, y, bitmap, 16, 16, color);
}

enum Align { AL_LEFT, AL_CENTER, AL_RIGHT };

// draw text with its top-left / top-center / top-right at (x, y)
static int16_t drawText(const char *s, int16_t x, int16_t y, const GFXfont *font, uint8_t size,
                        uint16_t color, Align al = AL_LEFT) {
  int16_t bx, by; uint16_t bw, bh;
  display.setFont(font);
  display.setTextSize(size);
  display.setTextColor(color);
  display.getTextBounds(s, 0, 0, &bx, &by, &bw, &bh);
  int16_t x0 = x;
  if (al == AL_CENTER) x0 = x - bw / 2;
  else if (al == AL_RIGHT) x0 = x - bw;
  display.setCursor(x0 - bx, y - by);
  display.print(s);
  return bw;
}

static void textSize(const char *s, const GFXfont *font, uint8_t size, uint16_t &w, uint16_t &h) {
  int16_t bx, by;
  display.setFont(font);
  display.setTextSize(size);
  display.getTextBounds(s, 0, 0, &bx, &by, &w, &h);
}

// 16x16 icon drawn at twice its size (32x32 cell); Adafruit GFX has no bitmap scaling
static void drawIcon2x(int16_t x, int16_t y, const unsigned char *bitmap, uint16_t color) {
  for (int row = 0; row < 16; row++)
    for (int col = 0; col < 16; col++)
      if (bitmap[row * 2 + col / 8] & (0x80 >> (col % 8)))
        display.fillRect(x + col * 2, y + row * 2, 2, 2, color);
}

// solid pointer (the silhouette of the U+27A4 arrow) of length len, centred at (cx, cy),
// pointing at angleDeg: -90 up, 0 right (flat), 90 down. Screen y grows downwards, so the
// NightscoutMon angle convention rotates directly.
static void drawPointer(int cx, int cy, int angleDeg, int len, uint16_t color) {
  float a = angleDeg * (float)PI / 180.0f, ca = cosf(a), sa = sinf(a);
  auto rx = [&](float x, float y) { return (int16_t)lroundf(cx + x * ca - y * sa); };
  auto ry = [&](float x, float y) { return (int16_t)lroundf(cy + x * sa + y * ca); };
  float half = len / 2.0f, wing = len * 0.42f, notch = -half + len * 0.3f;
  // two triangles sharing the tip-notch edge give the concave back
  display.fillTriangle(rx(half, 0), ry(half, 0), rx(-half, -wing), ry(-half, -wing),
                       rx(notch, 0), ry(notch, 0), color);
  display.fillTriangle(rx(half, 0), ry(half, 0), rx(notch, 0), ry(notch, 0),
                       rx(-half, wing), ry(-half, wing), color);
}

// trend: one pointer for flat / 45 / single, two stacked for double up / down (xDrip's
// double arrows), which are otherwise only 15 degrees apart from the single ones
static void drawTrend(int cx, int cy, int angle, uint16_t color) {
  if (angle <= -90 || angle >= 90) {
    drawPointer(cx, cy - 13, angle, 24, color);
    drawPointer(cx, cy + 13, angle, 24, color);
  } else {
    drawPointer(cx, cy, angle, 36, color);
  }
}

// colour band for the current value: 0 normal, 1 yellow warning, 2 red alarm
static int valueLevel() {
  if (!gs.hasData) return 0;
  if (gs.mgdl < cfg.redLow || gs.mgdl > cfg.redHigh) return 2;
  if (gs.mgdl < cfg.yellowLow || gs.mgdl > cfg.yellowHigh) return 1;
  return 0;
}

// ---- screen parts ---------------------------------------------------------------

void EpdUi::drawHeader() {
  // from the right: battery icon, battery %, link icon, snooze clock; reading time
  // on the left. The icons are the 16x16 art at 2x; the link / clock art has 4 blank
  // columns on each side (8 px at 2x), which the fit test counts as spacing.
  int pct = battery.percent();
  char pt[8] = "";
  if (pct >= 0) snprintf(pt, sizeof(pt), "%d%%", pct);
  char t[12] = "";
  if (gs.hasData && gs.readingUtc) timeService.formatTime(gs.readingUtc, t, sizeof(t));
  bool snoozed = alarms.isSnoozed();

  // the percentage only when there is room: 11 pt, else 9 pt, else dropped, keeping
  // the time at 18 pt as long as possible (a 12 h time is wider and may drop to 12 pt).
  const GFXfont *cand[][2] = {
    { &FreeSansBold18pt7b, &FreeSansBold11pt7b }, { &FreeSansBold18pt7b, &FreeSansBold9pt7b },
    { &FreeSansBold18pt7b, nullptr },
    { &FreeSansBold12pt7b, &FreeSansBold11pt7b }, { &FreeSansBold12pt7b, &FreeSansBold9pt7b },
    { &FreeSansBold12pt7b, nullptr } };
  const GFXfont *tf = &FreeSansBold12pt7b, *pf = nullptr;
  uint16_t w, h, tw = 0, th = 0, pw = 0, ph = 0;
  int linkX = 0;
  for (auto &c : cand) {
    uint16_t ctw = 0, cth = 0, cpw = 0, cph = 0;
    if (t[0]) { textSize(t, c[0], 1, w, h); ctw = w; cth = h; }
    if (pt[0] && c[1]) { textSize(pt, c[1], 1, w, h); cpw = w; cph = h; }
    int lx = W - 32 - (cpw ? cpw + 6 : 0) - 32;          // link icon cell
    int leftmost = lx - (snoozed ? 32 : 0) + 8;           // first visible icon column
    tf = c[0]; pf = cpw ? c[1] : nullptr; tw = ctw; th = cth; pw = cpw; ph = cph; linkX = lx;
    if (2 + ctw + 4 <= leftmost) break;
  }

  int x = W - 32;
  if (battery.onUsb() && pct < 0) drawIcon2x(x, 0, plug_icon16x16, GxEPD_BLACK);
  else if (pct >= 0) {
    const unsigned char *ic = pct <= 12 ? bat0_icon16x16 : pct <= 40 ? bat1_icon16x16 :
                              pct <= 65 ? bat2_icon16x16 : pct <= 90 ? bat3_icon16x16 : bat4_icon16x16;
    uint16_t c = pct <= 12 ? GxEPD_RED : GxEPD_BLACK;
    drawIcon2x(x, 0, ic, c);
    if (pf) drawText(pt, x - 3, (HDR_H - ph) / 2, pf, 1, c, AL_RIGHT);
  }
  x = linkX;
  if (cfg.source == SRC_OBB) {
    ObbState s = obbState();
    uint16_t c = s == OBB_CONNECTED ? GxEPD_BLACK : GxEPD_RED;
    drawIcon2x(x, 0, bluetooth_icon16x16, c);
  } else if (cfg.source == SRC_MIBAND) {
    // in the power cycle the link is closed again before the screen refreshes:
    // black as long as xDrip has paired, red until the first key exchange
    bool ok = miBandIsAuthenticated() || (!cycleAwake() && cfg.mibandKeySet);
    drawIcon2x(x, 0, bluetooth_icon16x16, ok ? GxEPD_BLACK : GxEPD_RED);
  } else {
    drawIcon2x(x, 0, wifi2_icon16x16, wifiConnected() ? GxEPD_BLACK : GxEPD_RED);
  }
  if (snoozed) drawIcon2x(x - 32, 0, clock_icon16x16, GxEPD_RED);

  if (t[0]) drawText(t, 2, (HDR_H - th) / 2, tf, 1, GxEPD_BLACK);
}

void EpdUi::drawValue() {
  // a reading STALE_MIN or older is no longer shown at all: "---" without band or
  // pointer (the age on the right says how old it is); LATE_MIN..STALE_MIN is
  // crossed out
  bool stale = gs.hasData && gs.isStale();
  bool late = gs.hasData && !stale && (gs.isLate() || !gs.live);
  char v[12];
  if (stale) strlcpy(v, "---", sizeof(v));
  else gs.valueString(v, sizeof(v), cfg.isMgdl());
  // 28 pt digits (~40 px) leave room for the trend pointer on the right
  const GFXfont *font = strlen(v) > 4 ? &FreeSansBold18pt7b : &FreeSansBold28pt7b;
  uint16_t tw, th;
  textSize(v, font, 1, tw, th);
  // the band encloses value, pointer, delta and age: red / yellow fill outside the
  // colour range or while an alarm / warning is active, a rounded 2 px frame in range,
  // nothing once the value reads "---" (unless an alarm state says otherwise)
  int level = stale ? 0 : valueLevel();
  AlarmState as = alarms.state();
  int alarmLevel = (as == ALARM_ALARM_LOW || as == ALARM_ALARM_HIGH || as == ALARM_REMOTE) ? 2 :
                   (as == ALARM_NONE) ? 0 : 1;
  if (alarmLevel > level) level = alarmLevel;
  uint16_t fg = GxEPD_BLACK;
  if (level == 2) { display.fillRoundRect(2, BAND_TOP, W - 4, BAND_H, 8, GxEPD_RED); fg = GxEPD_WHITE; }
  else if (level == 1) { display.fillRoundRect(2, BAND_TOP, W - 4, BAND_H, 8, GxEPD_YELLOW); }
  else if (gs.hasData && !stale) {
    display.drawRoundRect(2, BAND_TOP, W - 4, BAND_H, 8, GxEPD_BLACK);
    display.drawRoundRect(3, BAND_TOP + 1, W - 6, BAND_H - 2, 7, GxEPD_BLACK);
  }
  bandFg = fg;
  int ty = VAL_TOP + (VAL_H - th) / 2;
  drawText(v, VAL_CX, ty, font, 1, fg, AL_CENTER);
  if (late) {
    // strike-through: the value can no longer be trusted
    int y = ty + th / 2;
    display.fillRect(VAL_CX - tw / 2 - 6, y - 2, tw + 12, 5, level == 2 ? GxEPD_WHITE : GxEPD_RED);
  }
  // trend pointer, right of the value, in the band's foreground colour
  if (gs.hasData && gs.arrowAngle != ARROW_HIDDEN && !stale)
    drawTrend(ARROW_CX, ARROW_CY, gs.arrowAngle, fg);
}

void EpdUi::drawTrendRow() {
  uint16_t tw, th;
  // delta (left)
  char d[12];
  if (gs.hasData && gs.isStale()) strlcpy(d, "---", sizeof(d));
  else gs.deltaString(d, sizeof(d), cfg.isMgdl());
  textSize(d, &FreeSansBold18pt7b, 1, tw, th);
  drawText(d, 10, TREND_Y + (TREND_H - th) / 2, &FreeSansBold18pt7b, 1, bandFg);
  // age (right)
  char age[16];
  if (!gs.hasData) age[0] = 0;
  else {
    int m = gs.minutesAgo();
    if (m < 60) snprintf(age, sizeof(age), "%d min", m);
    else if (m < 1440) snprintf(age, sizeof(age), "%dh%02d", m / 60, m % 60);
    else strlcpy(age, "old", sizeof(age));
  }
  if (!age[0]) return;
  textSize(age, &FreeSansBold18pt7b, 1, tw, th);
  // a late age is red, except on the red band where everything is white
  uint16_t c = gs.isLate() && bandFg != GxEPD_WHITE ? GxEPD_RED : bandFg;
  drawText(age, W - 10, TREND_Y + (TREND_H - th) / 2, &FreeSansBold18pt7b, 1, c, AL_RIGHT);
}

void EpdUi::drawGraph(int y0, int hgt) {
  // the last GRAPH_PTS samples (2 h), newest at the right edge. The scale follows the
  // data around the yellow band so the curve uses the full height instead of a fixed
  // 40..300 mg/dL range.
  const int x0 = GRAPH_X, gw = GRAPH_PTS * GRAPH_PITCH;
  int n = gs.histCount, first = n > GRAPH_PTS ? n - GRAPH_PTS : 0;
  float lo = cfg.yellowLow - 10, hi = cfg.yellowHigh + 10;
  for (int i = first; i < n; i++) {
    uint16_t v = gs.hist[i];
    if (v == 0) continue;
    if (v < lo) lo = v;
    if (v > hi) hi = v;
  }
  if (lo < 40) lo = 40;
  if (hi > 300) hi = 300;
  if (hi - lo < 50) hi = lo + 50;
  auto yOf = [&](float mg) {
    if (mg > hi) mg = hi; if (mg < lo) mg = lo;
    return (int)(y0 + hgt - 1 - (mg - lo) * (hgt - 1) / (hi - lo));
  };
  auto threshold = [&](int mg, uint16_t c) {
    if (mg >= lo && mg <= hi) display.drawFastHLine(x0, yOf(mg), gw, c);
  };
  threshold(cfg.yellowHigh, GxEPD_YELLOW);
  threshold(cfg.yellowLow, GxEPD_YELLOW);
  threshold(cfg.redHigh, GxEPD_RED);
  threshold(cfg.redLow, GxEPD_RED);
  for (int i = first; i < n; i++) {
    uint16_t v = gs.hist[i];
    if (v == 0) continue;
    int x = x0 + (GRAPH_PTS - (n - i)) * GRAPH_PITCH;
    uint16_t c = GxEPD_BLACK;
    if (v < cfg.redLow || v > cfg.redHigh) c = GxEPD_RED;
    display.fillCircle(x, yOf(v), 1, c);
    display.drawPixel(x, yOf(v) - 1, c);
  }
}

// info line (IOB / COB from Nightscout, or the phone's status line) beside the graph,
// on up to two rows split at a double space; text too wide stays on the bottom bar
bool EpdUi::drawSideText() {
  if (!gs.infoLine[0]) return false;
  char rows[2][48];
  int nr = 1;
  const char *s = gs.infoLine, *sep = strstr(s, "  ");
  if (sep) {
    size_t l = sep - s;
    if (l >= sizeof(rows[0])) l = sizeof(rows[0]) - 1;
    memcpy(rows[0], s, l); rows[0][l] = 0;
    while (*sep == ' ') sep++;
    strlcpy(rows[1], sep, sizeof(rows[1]));
    nr = 2;
  } else {
    strlcpy(rows[0], s, sizeof(rows[0]));
  }
  for (int i = 0; i < nr; i++) {
    uint16_t w, h;
    textSize(rows[i], &FreeSansBold11pt7b, 1, w, h);
    if (w > SIDE_W) return false;
  }
  for (int i = 0; i < nr; i++)
    drawText(rows[i], SIDE_X, GRAPH_Y + 2 + i * 20, &FreeSansBold11pt7b, 1, GxEPD_BLACK);
  return true;
}

void EpdUi::drawBottomBar(bool infoShown) {
  const int y = BAR_Y;
  const char *alarm = alarms.label();
  if (alarm[0]) {
    AlarmState s = alarms.state();
    bool red = s == ALARM_ALARM_LOW || s == ALARM_ALARM_HIGH || s == ALARM_REMOTE;
    display.fillRect(0, y, W, BAR_H, red ? GxEPD_RED : GxEPD_YELLOW);
    char txt[40];
    int sn = alarms.snoozeRemainingMin();
    if (sn) snprintf(txt, sizeof(txt), "%s  zz %d'", alarm, sn);
    else strlcpy(txt, alarm, sizeof(txt));
    uint16_t tw, th;
    const GFXfont *font = &FreeSansBold12pt7b;
    textSize(txt, font, 1, tw, th);
    if (tw > W - 4) { font = &FreeSansBold9pt7b; textSize(txt, font, 1, tw, th); }
    drawText(txt, W / 2, y + (BAR_H - th) / 2, font, 1, red ? GxEPD_WHITE : GxEPD_BLACK, AL_CENTER);
    return;
  }
  // status text: setup mode > connection state > info line (unless it is already
  // shown beside the graph). In the power cycle the radios are off between wakes,
  // so only a persistent failure of the last fetch is shown, never the transient
  // link state.
  char txt[96];
  if (setupServerAdvertising())
    snprintf(txt, sizeof(txt), "Setup: %s", cfg.name());
  else if (!cycleAwake() && cycleStatusText()[0])
    strlcpy(txt, cycleStatusText(), sizeof(txt));
  else if (!cycleAwake() && gs.infoLine[0] && !infoShown)
    strlcpy(txt, gs.infoLine, sizeof(txt));
  else if (!cycleAwake())
    txt[0] = 0;
  else if (cfg.source == SRC_OBB && obbState() != OBB_CONNECTED)
    snprintf(txt, sizeof(txt), "xDrip: %s", obbStateName());
  else if (cfg.source == SRC_MIBAND && !miBandIsAuthenticated())
    snprintf(txt, sizeof(txt), "xDrip: %s", miBandStateName());
  else if (SRC_IS_WIFI(cfg.source) && !wifiConnected())
    snprintf(txt, sizeof(txt), "Wi-Fi: %s", wifiFailText()[0] ? wifiFailText() : wifiStateName());
  else if (cfg.source == SRC_DEXCOM && dxStatus()[0])
    strlcpy(txt, dxStatus(), sizeof(txt));
  else if (cfg.source == SRC_LIBRE && llStatus()[0])
    strlcpy(txt, llStatus(), sizeof(txt));
  else if (gs.infoLine[0] && !infoShown)
    strlcpy(txt, gs.infoLine, sizeof(txt));
  else
    txt[0] = 0;
  if (txt[0]) {
    uint16_t tw, th;
    textSize(txt, &FreeSans9pt7b, 1, tw, th);
    display.drawFastHLine(0, y, W, GxEPD_BLACK);
    drawText(txt, W / 2, y + 1 + (BAR_H - 1 - th) / 2, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);
  }
}

// ---- rendering ------------------------------------------------------------------

// what the panel currently shows, kept across deep sleep so a wake only
// refreshes when something visible changed
struct UiRtc {
  uint32_t magic;
  int64_t  lastRenderUtc;
  int16_t  lastAgeShown;
  uint8_t  lastStale;         // 0 fresh, 1 crossed out (late), 2 "---" (stale)
  uint8_t  lastLive;          // BG page (1) or status page (0) on the panel
  uint8_t  lastSetup;         // setup banner shown
  char     lastStatus[48];    // source status text shown on the status page
};
#define UI_MAGIC 0x55495254UL
RTC_DATA_ATTR static UiRtc s_rtc;

// how the reading age is rendered: 0 fresh, 1 crossed out, 2 "---"
static uint8_t ageState() {
  if (!gs.hasData) return 0;
  return gs.isStale() ? 2 : gs.isLate() ? 1 : 0;
}

static double sinceLastRender() {
  if (s_rtc.magic != UI_MAGIC) return 1e9;
  double d = difftime(time(nullptr), (time_t)s_rtc.lastRenderUtc);
  return d < 0 ? 1e9 : d;     // clock jumped: treat as long ago
}

void EpdUi::ensureInit() {
  if (inited) return;
  digitalWrite(PIN_EPD_PWR, LOW);         // panel supply on (already on, see PowerCycle)
  SPI.begin(PIN_EPD_SCK, -1, PIN_EPD_MOSI, PIN_EPD_CS);
  display.init(0, true, 2, false);
  display.setRotation(0);
  inited = true;
}

// source name for the status page, wrapped on two short lines when needed
static const char *sourceTitle() {
  switch (cfg.source) {
    case SRC_OBB:        return "xDrip / AAPS via phone";
    case SRC_MIBAND:     return "xDrip Mi Band";
    case SRC_NIGHTSCOUT: return "Nightscout";
    case SRC_DEXCOM:     return "Dexcom Share";
    case SRC_LIBRE:      return "LibreLinkUp";
    default:             return "?";
  }
}

void EpdUi::drawStatusPage() {
  drawHeader();
  drawText(cfg.name(), W / 2, 34, &FreeSansBold12pt7b, 1, GxEPD_BLACK, AL_CENTER);
  char line[48];
  int pct = battery.percent();
  if (pct >= 0) snprintf(line, sizeof(line), "v" WSMON_VERSION "  battery %d%%", pct);
  else          snprintf(line, sizeof(line), "v" WSMON_VERSION "  on USB");
  drawText(line, W / 2, 58, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);

  if (setupServerAdvertising()) {
    // the Android app over Bluetooth, or any browser through the open access
    // point the device runs while in setup mode (WebSetup)
    display.fillRoundRect(6, 78, W - 12, 66, 6, GxEPD_YELLOW);
    drawText("Setup mode", W / 2, 81, &FreeSansBold9pt7b, 1, GxEPD_BLACK, AL_CENTER);
    drawText("app  or  Wi-Fi network:", W / 2, 97, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);
    drawText(cfg.name(), W / 2, 112, &FreeSansBold9pt7b, 1, GxEPD_BLACK, AL_CENTER);
    char url[40];
    snprintf(url, sizeof(url), "and open %s", webSetupApIp());
    drawText(url, W / 2, 127, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);
  }

  drawText(sourceTitle(), W / 2, 148, &FreeSansBold9pt7b, 1, GxEPD_BLACK, AL_CENTER);
  cycleSourceStatus(line, sizeof(line));
  // "source: state" -> the state part fits below the title
  const char *state = strchr(line, ':');
  state = state ? state + 1 : line;
  while (*state == ' ') state++;
  bool bad = strstr(line, "fail") || strstr(line, "bad") || strstr(line, "not ") || strstr(line, "error") ||
             strstr(line, "HTTP") || strstr(line, "locked") || strstr(line, "no ");
  drawText(state, W / 2, 164, &FreeSans9pt7b, 1, bad ? GxEPD_RED : GxEPD_BLACK, AL_CENTER);
  drawText("waiting for the first reading", W / 2, 182, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);
}

void EpdUi::render() {
  rendering = true;
  ensureInit();
  display.setFullWindow();
  display.setRotation(0);
  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    if (!gs.live) {
      drawStatusPage();
    } else {
      drawHeader();
      drawValue();
      drawTrendRow();
      drawGraph(GRAPH_Y, GRAPH_H);
      bool side = drawSideText();
      drawBottomBar(side);
    }
  } while (display.nextPage());
  display.hibernate();
  s_rtc.magic = UI_MAGIC;
  s_rtc.lastRenderUtc = (int64_t)time(nullptr);
  s_rtc.lastAgeShown = gs.hasData ? (int16_t)gs.minutesAgo() : -1;
  s_rtc.lastStale = ageState();
  s_rtc.lastLive = gs.live;
  cycleSourceStatus(s_rtc.lastStatus, sizeof(s_rtc.lastStatus));
  s_rtc.lastSetup = setupServerAdvertising();
  rendering = false;
}

void EpdUi::begin(bool splash) {
  pinMode(PIN_EPD_PWR, OUTPUT);
  if (!splash) return;                    // woke from deep sleep: the panel keeps its image
  ensureInit();
  display.setFullWindow();
  display.firstPage();
  do {
    display.fillScreen(GxEPD_WHITE);
    drawText("WaveshareMon", W / 2, 60, &FreeSansBold12pt7b, 1, GxEPD_BLACK, AL_CENTER);
    drawText("v" WSMON_VERSION, W / 2, 90, &FreeSans9pt7b, 1, GxEPD_BLACK, AL_CENTER);
    drawText(cfg.name(), W / 2, 130, &FreeSans9pt7b, 1, GxEPD_RED, AL_CENTER);
  } while (display.nextPage());
  display.hibernate();
  s_rtc.magic = UI_MAGIC;
  s_rtc.lastRenderUtc = (int64_t)time(nullptr);
  s_rtc.lastAgeShown = -1;
  s_rtc.lastStale = false;
  s_rtc.lastLive = 2;                     // neither page yet: the first tick redraws
  s_rtc.lastStatus[0] = 0;
  redrawPending = true;                   // first data screen after boot
}

void EpdUi::powerDown() {
  if (inited) display.hibernate();
  // the panel rail stays on: it also powers the RTC (see PowerCycle.cpp)
}

bool EpdUi::due() {
  bool d = redrawPending;
  bool awake = cycleAwake();
  if (gs.dataChanged)       { gs.dataChanged = false; d = true; }
  if (alarms.stateChanged)  { alarms.stateChanged = false; d = true; }
  // link state only matters on the always-on screen; in the power cycle the
  // radios go up and down on every wake
  if (obbStateChanged)      { obbStateChanged = false; if (awake) d = true; }
  if (wifiStateChanged)     { wifiStateChanged = false; if (awake) d = true; }
  if (s_rtc.magic != UI_MAGIC) return true;
  if ((bool)s_rtc.lastLive != gs.live) return true;            // page switch
  if (!gs.live) {
    // status page: redraw when the source state or the setup banner changed
    char st[48];
    cycleSourceStatus(st, sizeof(st));
    if (strcmp(st, s_rtc.lastStatus) != 0) d = true;
    if ((bool)s_rtc.lastSetup != setupServerAdvertising()) d = true;
    return d;
  }
  // age display: every 5 minutes of age, with or without new readings (in the
  // power cycle that is every wake), and at once when the value gets crossed
  // out or replaced by "---"
  if (gs.hasData) {
    int age = gs.minutesAgo();
    if (ageState() != s_rtc.lastStale) d = true;
    else if (age >= s_rtc.lastAgeShown + 5 || age < s_rtc.lastAgeShown) d = true;
  }
  return d;
}

void EpdUi::tick() {
  if (rendering || !cycleAwake()) return;   // sleeping modes render in flush()
  if (!due()) return;
  // the panel needs ~20 s per refresh; never refresh more often than every 25 s
  if (sinceLastRender() < 25) { redrawPending = true; return; }
  redrawPending = false;
  render();
}

void EpdUi::flush() {
  if (rendering) return;
  if (!due()) return;
  redrawPending = false;
  render();
}
