"""Convert a TrueType font into an Adafruit GFX font header (same layout and
metrics as Adafruit's fontconvert: 141 dpi, 1 - bitmap top as yOffset).

    python Scripts/gfxfont.py FreeSansBold.ttf 11 > FreeSansBold11pt7b.h
    python Scripts/gfxfont.py FreeSansBold.ttf 28 0x2D 0x39 > FreeSansBold28pt7b.h   # "-" .. "9" only

Requires Pillow. Used for the sizes the Adafruit GFX library does not ship
(GNU FreeFont FreeSansBold.ttf, GPL with font exception, is not included here:
https://ftp.gnu.org/gnu/freefont/).
"""
import os, sys
from PIL import Image, ImageDraw, ImageFont

DPI = 141
FIRST, LAST = 0x20, 0x7E

def main():
    path, pt = sys.argv[1], int(sys.argv[2])
    global FIRST, LAST
    if len(sys.argv) > 4: FIRST, LAST = int(sys.argv[3], 0), int(sys.argv[4], 0)
    name = os.path.splitext(os.path.basename(path))[0].replace("-", "") + f"{pt}pt7b"
    px = pt * DPI / 72.0
    font = ImageFont.truetype(path, px)
    ascent, descent = font.getmetrics()
    bitmaps, glyphs = [], []
    for code in range(FIRST, LAST + 1):
        ch = chr(code)
        adv = int(round(font.getlength(ch)))
        l, t, r, b = font.getbbox(ch)
        w, h = r - l, b - t
        off = len(bitmaps)
        if w > 0 and h > 0 and ch != " ":
            img = Image.new("L", (w, h), 0)
            ImageDraw.Draw(img).text((-l, -t), ch, font=font, fill=255)
            bits = [1 if img.getpixel((x, y)) >= 128 else 0 for y in range(h) for x in range(w)]
            # trim rows/cols that thresholded to nothing? keep the box: simpler and safe
            byte = 0; n = 0
            for bit in bits:
                byte = (byte << 1) | bit; n += 1
                if n == 8: bitmaps.append(byte); byte = 0; n = 0
            if n: bitmaps.append(byte << (8 - n))
            glyphs.append((off, w, h, adv, l, t - ascent, ch))
        else:
            glyphs.append((off, 0, 0, adv, 0, 1, ch))
    yadv = int(round((ascent + descent) * 1.0))
    out = sys.stdout
    out.write("#pragma once\n#include <Adafruit_GFX.h>\n\n")
    out.write(f"// {name}: generated by Scripts/gfxfont.py from {os.path.basename(path)} at {pt} pt, {DPI} dpi\n\n")
    out.write(f"const uint8_t {name}Bitmaps[] PROGMEM = {{\n")
    for i in range(0, len(bitmaps), 12):
        out.write("    " + ", ".join(f"0x{b:02X}" for b in bitmaps[i:i + 12]) + ",\n")
    out.write("};\n\n")
    out.write(f"const GFXglyph {name}Glyphs[] PROGMEM = {{\n")
    for off, w, h, adv, xo, yo, ch in glyphs:
        out.write(f"    {{{off}, {w}, {h}, {adv}, {xo}, {yo}}}, // 0x{ord(ch):02X} '{ch}'\n")
    out.write("};\n\n")
    out.write(f"const GFXfont {name} PROGMEM = {{(uint8_t *){name}Bitmaps, (GFXglyph *){name}Glyphs, 0x{FIRST:02X}, 0x{LAST:02X}, {yadv}}};\n")
    out.write(f"\n// Approx. {len(bitmaps) + len(glyphs) * 7 + 7} bytes\n")

if __name__ == "__main__":
    main()
